name = "bushcraftchina2026"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bushcraftchina2026"
preview_bucket_name = "bushcraftchina2026-dev"
