name = "bushcraft-exhibition"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bushcraft-exhibition"
preview_bucket_name = "bushcraft-exhibition-dev"
